-
    stream_specifier: wi24
    stream_name: Winter 2024, Math 106
    invalid_emoji: octopus
    labeling_scheme: StandardLabelingScheme
    labeler_config: 
        start_date: 2024-01-08
        due_time: 6
        max_week: 10
        due_days: ['mon', 'wed', 'fri']
        exceptions: []
-
    stream_specifier: sp23
    stream_name: Spring 2023, Math 11
    invalid_emoji: octopus
    labeling_scheme: StandardLabelingScheme
    labeler_config: 
        start_date: 2023-04-03
        due_time: 7
        max_week: 10
        due_days: ['mon', 'wed', 'fri']
        exceptions: ['w1mon', 'w4mon', 'w4wed', 'w6wed', 'w8mon', 'w8wed', 'w8fri', 'w10wed', 'w10fri']
-
    stream_specifier: wi23
    stream_name: Winter 2023, Math 187A
    invalid_emoji: octopus
    labeling_scheme: StandardLabelingScheme
    labeler_config: 
        start_date: 2023-01-09
        due_time: 16
        max_week: 10
        due_days: ['tue', 'thu']
