-
    stream_specifier: sp23
    stream_name: Spring 2023, Math 11
    invalid_emoji: octopus
    labeling_scheme: StandardLabelingScheme
    labeler_config: 
        start_date: 2023-04-03
        due_time: 16
        max_week: 10
        due_days: ['tue', 'thu']
-
    stream_specifier: wi23
    stream_name: Winter 2023, Math 187A
    invalid_emoji: octopus
    labeling_scheme: StandardLabelingScheme
    labeler_config: 
        start_date: 2023-01-09
        due_time: 16
        max_week: 10
        due_days: ['tue', 'thu']
